

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_NAME: test
      DB_USER: postgres
      DB_PASS: 123456
      DB_HOST: db
      DB_PORT: 5432
      PORT: 3000
    ports:
      - "3000:3000"
    command: ["npx", "ts-node", "./src/app.ts"]
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app

volumes:
  pgdata:
